name: Artifact
on: push

env:
  ARTIFACT_NAME:  myartifact

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Check code
      use: actions/checkout@v2
    - name: create artifact
      use: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .